// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjUiT_dC-TmdjKA3JR9_zjdTdWSloVYQY',
    appId: '1:152442875734:web:59fd219a52ecc0231df0f7',
    messagingSenderId: '152442875734',
    projectId: 'mahjong-movers',
    authDomain: 'mahjong-movers.firebaseapp.com',
    storageBucket: 'mahjong-movers.appspot.com',
    measurementId: 'G-ZPMBY4D119',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQPSzPUDkuLwnaUY1_bo-VucEpDu-oknc',
    appId: '1:152442875734:android:b14d3093dd8ede9b1df0f7',
    messagingSenderId: '152442875734',
    projectId: 'mahjong-movers',
    storageBucket: 'mahjong-movers.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDCrvU7PpeWR5Etm-Hzlig-GumGr1PL2M',
    appId: '1:152442875734:ios:110c1133ddd804f51df0f7',
    messagingSenderId: '152442875734',
    projectId: 'mahjong-movers',
    storageBucket: 'mahjong-movers.appspot.com',
    iosClientId:
        '152442875734-oki562if7e75fi04ssbmgc49t0ai7p30.apps.googleusercontent.com',
    iosBundleId: 'com.example.mahjongMovers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDCrvU7PpeWR5Etm-Hzlig-GumGr1PL2M',
    appId: '1:152442875734:ios:110c1133ddd804f51df0f7',
    messagingSenderId: '152442875734',
    projectId: 'mahjong-movers',
    storageBucket: 'mahjong-movers.appspot.com',
    iosClientId:
        '152442875734-oki562if7e75fi04ssbmgc49t0ai7p30.apps.googleusercontent.com',
    iosBundleId: 'com.example.mahjongMovers',
  );
}
